<?php
require __DIR__ . '/bootstrap.php';

json_out([
    'ok' => true,
    'gemini_configured' => !empty($config['gemini_api_key']),
    'model' => 'gemini-3.8-live',
    'version' => '0.6.0',
    'mode' => 'client_preview',
    'sdk' => '@google/genai 2.25.0',
    'auth' => 'ephemeral_token',
    'voice_selection' => true,
    'transcription' => true,
    'mute_control' => true,
    'demo_knowledge' => true,
    'voice_url_sanitization' => true,
    'clickable_links' => true,
    'single_screen_call_mode' => true,
    'chat_popup' => true,
    'popup_call_controls' => true,
    'company_logo_core' => true,
    'simplified_header' => true,
    'header_removed' => true,
    'no_page_scroll' => true,
    'compact_chat_popup' => true,
    'chat_minimize_reopen' => true,
    'mic_status_fix' => true,
    'outbound_missions' => true,
    'custom_agent_identity' => true,
    'customer_speech_gate' => true,
    'manual_phone_link_dialing' => true,
    'viewport_locked' => true,
    'legacy_stt_tts_used' => false,
]);
